### ISSUE TITLE
VGG16 code

### ISSUE THREAD

**Issue by YifeiAI** [yzou2/cbst#1]
Thanks for sharing the code! I am just wondering if you could also share the code for vgg16 structure?

**Comment by yzou2** [comment]
> Thanks for sharing the code! I am just wondering if you could also share the code for vgg16 structure?

Thanks for your interests of our work! We are implementing self-training in Pytorch. We will release the Pytorch version of self-training with vgg16 soon.

**Comment by amiltonwong** [comment]
Hi, @yzou2 ,
When will Pytorch version of self-training code be released?
THX!
