### ISSUE TITLE
About the basenet

### ISSUE THREAD

**Issue by qiaozhuocheng** [yzou2/cbst#11]
Sorry to bother you again,I am very interested about your ECCV PAPER`Domain Adaptation for Semantic Segmentation via Class-Balanced Self-Training`.I found that you have choosed both FCN8s-VGG16，and RESNET-38 as basenet, and this project is based on the RESNET. If I want to reproduce the same result base in  FCN8s-VGG16，how can I change your code? It's very pleasant if you can answer me more explicitly since I am a freshman.

**Comment by yzou2** [comment]
I suggest you to modify the CRST/CBST pytorch baseline (https://github.com/yzou2/CRST) Without confidence regularizer, CRST degenerates to CBST. It's much simpler to code and change base network in that baseline. You can get familiar with some FCN8s-VGG16 supervised training pytorch code to start. Then it's very straight forward to change the basenet in our CRST code.

**Comment by qiaozhuocheng** [comment]
Thank you for prompt reply and I will try it with your suggestion
