### ISSUE TITLE
Prior_array.mat file generation

### ISSUE THREAD

**Issue by Medj9** [yzou2/cbst#13]
Hi @yzou2 , Can you provide script for prior array generation. Thanks!!

**Comment by yzou2** [comment]
You can play with the code in the link of 
https://www.dropbox.com/s/6lqibugapbw52sr/spatial_prior_code.rar?dl=0

First run the frequency_map.m to generate frequency map and then generate priors .mat file by imagesc_sp.m.

Also you can check our python code to generate priors .npy file by the following python code.

https://www.dropbox.com/s/ob34beq2n7dofrv/spatial_prior.py?dl=0

**Comment by Medj9** [comment]
Thank you
