### ISSUE TITLE
Save confidence scores of target domain as class-wise vectors

### ISSUE THREAD

**Issue by Zhenghongwei0929** [yzou2/cbst#14]
Hi，@yzou2，saving confidence scores of target domain as class-wise vectors as the type of numpy， Isn’t it too big? In my experiment, the cpu utilization reached 200% and it was never unable to continue.

**Comment by yzou2** [comment]
Hi Hongwei, we downsample the score maps by 4 when saving them for later processing (ref: https://github.com/yzou2/CBST/blob/master/issegm/solve_ST.py#L864-L865). If your machine cannot handle it, you can increase the downsampling rate by 8 or 16. As far as I remember, it won't effect the results too much.

**Comment by Zhenghongwei0929** [comment]
Thank you very much for your response. It may be that my dataset is relatively larger than Cityscapse or GTA5, so it is difficult to directly store the probmap of all data. At present, I increased the downsampling rate and the problem was solved.
