### ISSUE TITLE
Pytorch version?

### ISSUE THREAD

**Issue by fabvio** [yzou2/cbst#2]
Hi, first of all congratulations for the great work. Do you plan to release a Pytorch version of your implementation? Do you have any estimated release date? Thanks in advance

**Comment by tht106** [comment]
The code is tested in Ubuntu 16.04. It is implemented based on MXNet 1.3.0 and Python 2.7.12. For GPU usage, the maximum GPU memory consumption is about 7GB in a single NVIDIA TiTan Xp.

**Comment by fabvio** [comment]
Well, this doesn't really answer to the question. However, I implemented my own version of the method in pytorch. Thank you anyways.

**Comment by ghost** [comment]
@fabvio May i know if you got same result as mentioned in this paper? Can you share the code in pytorch version? Many thanks if you can sharing the code.

**Comment by fabvio** [comment]
I didn't test it directly on the dataset used for the paper, but I have to say that the results were good. Unfortunately my code is IP restricted, but it wasn't difficult to implement it, so I definitely advise you to give it a try.

**Comment by ghost** [comment]
OK, many thanks for your information!

**Comment by yzou2** [comment]
@jiaxing002 Check out our new paper "Confidence Regularized Self-Training" (ICCV 2019, Oral) (https://arxiv.org/pdf/1908.09822.pdf), which investigates confidence regularization in self-training systematically. The pytorch code based on CBST will be released soon before ICCV 2019.

**Comment by imtiazziko** [comment]
Hi Guys. Is the pytorch code coming soon? we are eagerly waiting for it. Thanx for letting us know.

**Comment by yzou2** [comment]
> Hi Guys. Is the pytorch code coming soon? we are eagerly waiting for it. Thanx for letting us know.

Check our released pytorch code for GTA2Cityscapes: https://github.com/yzou2/CRST
