### ISSUE TITLE
pretrained file corrupted

### ISSUE THREAD

**Issue by Serge-weihao** [yzou2/cbst#3]
I found that your source model of gta is corrupted. Can you check it and provide the completed one?
https://www.dropbox.com/s/idnnk398hf6u3x9/gta_rna-a1_cls19_s8_ep-0000.params?dl=0

**Comment by yzou2** [comment]
I just test it without any problem. Can you post the error information? 

FYI, when I download the file using wget, the file extension it .params?dl=0. Just changing the extension to be .params can make it work.

**Comment by Serge-weihao** [comment]
@yzou2 
![error](https://user-images.githubusercontent.com/40890323/52322059-86272100-2a12-11e9-8634-dabb36c83754.jpg)
I use dropbox to download it, because it is not conveninent to use wget in server under GFW.

**Comment by yzou2** [comment]
I notice your mxnet version is 0.10.1. I just test my code in 1.3.0. Updating your mxnet to 1.3.0. may solve your problem.

**Comment by Serge-weihao** [comment]
@yzou2 It works for mxnet 1.3.0, thanks.
![mx13](https://user-images.githubusercontent.com/40890323/52327784-40755300-2a28-11e9-8729-265dd8a03b85.jpg)
