### ISSUE TITLE
About the Results

### ISSUE THREAD

**Issue by Serge-weihao** [yzou2/cbst#4]
@yzou2 
![100001](https://user-images.githubusercontent.com/40890323/52597959-5bfcb580-2e8f-11e9-9453-1320eddc9bcf.png)
Are your results of cityscapes from validation set or test set?

**Comment by yzou2** [comment]
> @yzou2 
> Are your results of cityscapes from validation set or test set?

As mentioned in the paper, we follow the standard protocol and  the results of cityscapes come from validation set.
