### ISSUE TITLE
About label definition of SYNTHIA

### ISSUE THREAD

**Issue by zhyx12** [yzou2/cbst#7]
As the label maps in labels_synthia.py and labels_cityscapes_synthia.py show, there is **16** classes in both training and testing phase for SYNTHIA16 settings. And the results in paper show SYNTHIA13 is just evaluated among 13 classes based on SYNTHIA16 results.
I'm just making sure that for SYNTHIA16 and SYNTHIA13, there are 16 classes in training and testing, **not** 19 or 13. Am I right?

**Comment by yzou2** [comment]
Yes, your understanding is correct. We evaluate among 13 classes based on SYNTHIA16 model and calculate the mIoU of those 13 classes.
